const notifications = [
  {
    id : 1, 
    title: "Rappel de paiement en retard",
    date: "23/03/2025",
    type: "paiement",
    icon: "x",
    iconColor: "rgb(248, 0, 0)",
    message: "Votre paiement du 23/03/2025 n’a pas été effectué. Merci de le régler au plus vite.",
  },
  {
    id : 2, 
    title: "Changement d’horaire",
    date: "24/03/2025",
    type: "horaire",
    icon: "clock",
    iconColor: "#15B99B",
    message: "L’horaire de vos cours/examens a été modifié. Consultez les détails dès maintenant.",
  },
  {
    id : 4, 
    title: "Alerte maintenance",
    date: "24/03/2025",
    type: "maintenance",
    icon: "alert",
    iconColor: "rgb(255, 157, 0)",
    message: "Un problème technique est en cours. Nos équipes travaillent à le résoudre. Merci de votre patience.",
  },
  {
    id : 3, 
    title: "Résultats disponibles",
    date: "24/03/2025",
    type: "résultats",
    icon: "megaphone",
    iconColor: "#15B99B",
    message: "Les résultats de vos examens sont en ligne. Consultez-les dès maintenant !",
  },
  
  {
    id : 5, 
    title: "Nouvelle mise à jour disponible",
    date: "24/03/2025",
    type: "mise à jour",
    icon: "star",
    iconColor: "#15B99B",
    message: "Découvrez nos nouvelles fonctionnalités et améliorations. Mettez à jour l’application dès maintenant !",
  },
  {
    id : 6, 
    title: "Nouvel événement sur le campus",
    date: "24/03/2025",
    type: "événement",
    icon: "megaphone",
    iconColor: "#15B99B",
    message: "Ne manquez pas l'événement de BLOCK CHAIN le 24/03/2025. Rejoignez-nous pour un moment inoubliable !",
  },
  {
    id : 7, 
    title: "Rappel de paiement en retard",
    date: "23/03/2025",
    type: "paiement",
    icon: "x",
    iconColor: "rgb(248, 0, 0)",
    message: "Votre paiement du 23/03/2025 n’a pas été effectué. Merci de le régler au plus vite.",
  },
  {
    id : 8, 
    title: "Changement d’horaire",
    date: "24/03/2025",
    type: "horaire",
    icon: "clock",
    iconColor: "#15B99B",
    message: "L’horaire de vos cours/examens a été modifié. Consultez les détails dès maintenant.",
  },
  {
    id : 9, 
    title: "Résultats disponibles",
    date: "24/03/2025",
    type: "résultats",
    icon: "megaphone",
    iconColor: "#15B99B",
    message: "Les résultats de vos examens sont en ligne. Consultez-les dès maintenant !",
  },
  {
    id : 10, 
    title: "Alerte maintenance",
    date: "24/03/2025",
    type: "maintenance",
    icon: "alert",
    iconColor: "rgb(255, 157, 0)",
    message: "Un problème technique est en cours. Nos équipes travaillent à le résoudre. Merci de votre patience.",
  },
  {
    id : 11, 
    title: "Nouvelle mise à jour disponible",
    date: "24/03/2025",
    type: "mise à jour",
    icon: "star",
    iconColor: "#15B99B",
    message: "Découvrez nos nouvelles fonctionnalités et améliorations. Mettez à jour l’application dès maintenant !",
  },
  {
    id : 12, 
    title: "Nouvel événement sur le campus",
    date: "24/03/2025",
    type: "événement",
    icon: "megaphone",
    iconColor: "#15B99B",
    message: "Ne manquez pas l'événement de BLOCK CHAIN le 24/03/2025. Rejoignez-nous pour un moment inoubliable !",
  },
];



export default notifications;